spring:
  redis:
    database: 10
    # Redis服务器地址
    host: 172.16.9.202
    # Redis服务器连接端口
    port: 6382
    # Redis服务器连接密码(默认为空)
    password: 123456
    # 连接超时时间(毫秒)
    timeout: 5000
    # Spring Boot 2.X需要如此配置，可选 jedis 或 lettuce
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制)
        max-active: 5
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0

