spring:
  profiles:
    active: dev
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    suffix: .html
  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册


server:
  port: 8010


logging:
  config: classpath:log4j2/log4j2.xml




